# Generated by Django 2.0.5 on 2018-05-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
                ('modifiedOn', models.DateTimeField(auto_now=True)),
                ('active', models.IntegerField(choices=[(0, 0), (2, 2)], default=2)),
                ('status', models.IntegerField(choices=[(0, 'This Week'), (2, 'Next Week')], default=0)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
